// Decompiled with JetBrains decompiler
// Type: Gbs.Helpers.Egais.DocBody
// Assembly: Market, Version=6.6.12.2634, Culture=neutral, PublicKeyToken=null
// MVID: 1F63B1D6-03C1-4223-9A1B-4EA2EB09E32F
// Assembly location: C:\Program Files (x86)\F-Lab\Market 6\Market.exe

using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

#nullable disable
namespace Gbs.Helpers.Egais
{
  [GeneratedCode("xsd", "4.8.3928.0")]
  [DebuggerStepThrough]
  [DesignerCategory("code")]
  [XmlType(Namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")]
  [Serializable]
  public class DocBody
  {
    private object itemField;
    private ItemChoiceType itemElementNameField;

    [XmlElement("ActCancelOnlineOrder", typeof (ActCancelOnlineOrderType))]
    [XmlElement("ActChargeOn", typeof (ActChargeOnType))]
    [XmlElement("ActChargeOnShop_v2", typeof (ActChargeOnShopType_v2))]
    [XmlElement("ActChargeOn_v2", typeof (ActChargeOnType_v2))]
    [XmlElement("ActConfirmOnlineOrder", typeof (ActConfirmOnlineOrderType))]
    [XmlElement("ActFixBarCode", typeof (ActFixBarCode))]
    [XmlElement("ActInventory", typeof (ActInventoryType))]
    [XmlElement("ActInventoryInformBReg", typeof (ActInventoryInformBReg))]
    [XmlElement("ActInventoryInformF2Reg", typeof (ActInventoryInformF2Reg))]
    [XmlElement("ActReceiptOnlineOrder", typeof (ActReceiptOnlineOrderType))]
    [XmlElement("ActUnFixBarCode", typeof (ActUnFixBarCode))]
    [XmlElement("ActWriteOff", typeof (ActWriteOffType))]
    [XmlElement("ActWriteOffShop_v2", typeof (ActWriteOffShopType_v2))]
    [XmlElement("ActWriteOff_v2", typeof (ActWriteOffType_v2))]
    [XmlElement("ActWriteOff_v3", typeof (ActWriteOffType_v3))]
    [XmlElement("AscpNav", typeof (AscpNav))]
    [XmlElement("Asiiu", typeof (Asiiu))]
    [XmlElement("AsiiuSign", typeof (Asiiu))]
    [XmlElement("AsiiuTime", typeof (AsiiuTime))]
    [XmlElement("AsiiuTimeSign", typeof (AsiiuTime))]
    [XmlElement("CancelRoute", typeof (CancelRoute))]
    [XmlElement("CarrierNotice", typeof (CarrierNotice))]
    [XmlElement("CarrierNotice_v4", typeof (CarrierNotice_v4))]
    [XmlElement("ChequeV3", typeof (ChequeV3Type))]
    [XmlElement("ClaimIssueFSM", typeof (ClaimIssueFSMType))]
    [XmlElement("ConfirmRepealWB", typeof (ConfirmRepealWB))]
    [XmlElement("ConfirmTicket", typeof (ConfirmTicketType))]
    [XmlElement("DebtAbsence", typeof (DebtAbsenceType))]
    [XmlElement("InfoVersionTTN", typeof (InfoVersionTTN))]
    [XmlElement("InvoiceExportFSM", typeof (InvoiceExportFSMType))]
    [XmlElement("InvoiceIssueAM", typeof (InvoiceIssueAMType))]
    [XmlElement("InvoicePlannedImport", typeof (InvoicePlannedImportType))]
    [XmlElement("ManufacturingNoticeFSM", typeof (ManufacturingNoticeFSM))]
    [XmlElement("NotificationsBeginningTurnover", typeof (NotificationsBeginningTurnoverType))]
    [XmlElement("QueryAP", typeof (QueryParameters))]
    [XmlElement("QueryAP_v2", typeof (QueryParameters))]
    [XmlElement("QueryAP_v3", typeof (QueryParameters))]
    [XmlElement("QueryBarcode", typeof (QueryBarcode))]
    [XmlElement("QueryClientVersion", typeof (QueryParameters))]
    [XmlElement("QueryClients", typeof (QueryParameters))]
    [XmlElement("QueryClients_v2", typeof (QueryParameters))]
    [XmlElement("QueryForm2History", typeof (QueryParameters))]
    [XmlElement("QueryFormA", typeof (QueryFormAB))]
    [XmlElement("QueryFormB", typeof (QueryFormAB))]
    [XmlElement("QueryFormBHistory", typeof (QueryParameters))]
    [XmlElement("QueryFormF1", typeof (QueryFormF1F2))]
    [XmlElement("QueryFormF2", typeof (QueryFormF1F2))]
    [XmlElement("QueryGenerationOpenKey", typeof (QueryGenerationOpenKeyType))]
    [XmlElement("QueryHistoryRestShop", typeof (QueryParameters))]
    [XmlElement("QueryNATTN", typeof (QueryParameters))]
    [XmlElement("QueryParentHistForm2", typeof (QueryParameters))]
    [XmlElement("QueryPlaceOfBusiness", typeof (QueryParameters))]
    [XmlElement("QueryRejectRepImported", typeof (QueryRejectRepImported))]
    [XmlElement("QueryRejectRepProduced", typeof (QueryRejectRepProduced))]
    [XmlElement("QueryResendDoc", typeof (QueryParameters))]
    [XmlElement("QueryRestBCode", typeof (QueryParameters))]
    [XmlElement("QueryRests", typeof (QueryParameters))]
    [XmlElement("QueryRestsShop_Mini", typeof (QueryParameters))]
    [XmlElement("QueryRestsShop_v2", typeof (QueryParameters))]
    [XmlElement("QueryRests_Mini", typeof (QueryParameters))]
    [XmlElement("QueryRests_v2", typeof (QueryParameters))]
    [XmlElement("QuerySP", typeof (QueryParameters))]
    [XmlElement("QuerySP_v2", typeof (QueryParameters))]
    [XmlElement("QuerySSP", typeof (QueryParameters))]
    [XmlElement("QuerySSP_v2", typeof (QueryParameters))]
    [XmlElement("QueryWriteOffCheque", typeof (QueryParameters))]
    [XmlElement("RecheckNotificationsFSM", typeof (RecheckNotificationsFSMType))]
    [XmlElement("ReferenceOfDeficiencies", typeof (ReferenceOfDeficiencies))]
    [XmlElement("RejectionNoticeFSM", typeof (RejectionNoticeFSMType))]
    [XmlElement("RepImportedProduct", typeof (RepImportedType))]
    [XmlElement("RepImportedProduct_v3", typeof (RepImportedType_v3))]
    [XmlElement("RepImportedProduct_v4", typeof (RepImportedType_v4))]
    [XmlElement("RepInformF1Reg", typeof (RepPIInformF1RegType))]
    [XmlElement("RepProducedProduct", typeof (RepProducedType))]
    [XmlElement("RepProducedProduct_v3", typeof (RepProducedType_v3))]
    [XmlElement("RepProducedProduct_v4", typeof (RepProducedType_v4))]
    [XmlElement("ReplyAP", typeof (ReplyAP))]
    [XmlElement("ReplyAP_v2", typeof (ReplyAP_v2))]
    [XmlElement("ReplyAP_v3", typeof (ReplyAP_v3))]
    [XmlElement("ReplyBarcode", typeof (ReplyBarcode))]
    [XmlElement("ReplyClient", typeof (ReplyClient))]
    [XmlElement("ReplyClientVersion", typeof (ReplyClientVersion))]
    [XmlElement("ReplyClient_v2", typeof (ReplyClient_v2))]
    [XmlElement("ReplyForm1", typeof (ReplyForm1))]
    [XmlElement("ReplyForm2", typeof (ReplyForm2))]
    [XmlElement("ReplyFormA", typeof (ReplyFormA))]
    [XmlElement("ReplyFormB", typeof (ReplyFormB))]
    [XmlElement("ReplyGenerationOpenKey", typeof (ReplyGenerationOpenKeyType))]
    [XmlElement("ReplyHistForm2", typeof (ReplyHistForm2))]
    [XmlElement("ReplyHistFormB", typeof (ReplyHistFormB))]
    [XmlElement("ReplyHistoryShop", typeof (ReplyHistoryTransferShop))]
    [XmlElement("ReplyNoAnswerTTN", typeof (NoAnswerTTN))]
    [XmlElement("ReplyParentHistForm2", typeof (ReplyParentHistForm2))]
    [XmlElement("ReplyPlaceOfBusiness", typeof (ReplyPlaceOfBusiness))]
    [XmlElement("ReplyRestBCode", typeof (ReplyRestBCode))]
    [XmlElement("ReplyRests", typeof (ReplyRests))]
    [XmlElement("ReplyRestsShop_Mini", typeof (ReplyRestsShop_Mini))]
    [XmlElement("ReplyRestsShop_v2", typeof (ReplyRestsShop_v2))]
    [XmlElement("ReplyRests_Mini", typeof (ReplyRests_Mini))]
    [XmlElement("ReplyRests_v2", typeof (ReplyRests_v2))]
    [XmlElement("ReplySSP", typeof (ReplySSP))]
    [XmlElement("ReplySSP_v2", typeof (ReplySSP_v2))]
    [XmlElement("ReplySpirit", typeof (ReplySpirit))]
    [XmlElement("ReplySpirit_v2", typeof (ReplySpirit_v2))]
    [XmlElement("ReplyWriteOffCheque", typeof (ReplyWOCheque))]
    [XmlElement("ReportDestructionAMFSM", typeof (ReportDestructionAMFSMType))]
    [XmlElement("RequestAddFProducer", typeof (RequestAddFProducer))]
    [XmlElement("RequestAddProducts", typeof (RequestAddProducts))]
    [XmlElement("RequestAdjustmentData", typeof (RequestAdjustmentData))]
    [XmlElement("RequestBalanceTransfer", typeof (RequestBalanceTransfer))]
    [XmlElement("RequestManufacturerFSM", typeof (RequestManufacturerFSMType))]
    [XmlElement("RequestManufacturerFSMforCheck", typeof (RequestManufacturerFSMforCheckType))]
    [XmlElement("RequestRepealACO", typeof (RequestRepealACO))]
    [XmlElement("RequestRepealAWO", typeof (RequestRepealAWO))]
    [XmlElement("RequestRepealEAM", typeof (RequestRepealEAM))]
    [XmlElement("RequestRepealIAM", typeof (RequestRepealIAM))]
    [XmlElement("RequestRepealIPI", typeof (RequestRepealIPI))]
    [XmlElement("RequestRepealWB", typeof (RequestRepealWB))]
    [XmlElement("ReturnNoticeFSM", typeof (ReturnNoticeFSMType))]
    [XmlElement("Route", typeof (Route))]
    [XmlElement("TTNHistoryF2Reg", typeof (TTNHistoryF2Reg))]
    [XmlElement("TTNInformBReg", typeof (WayBillInformBRegType))]
    [XmlElement("TTNInformF2Reg", typeof (WayBillInformF2RegType))]
    [XmlElement("TTNIssueFSM", typeof (TTNIssueFSMType))]
    [XmlElement("TTNIssueReturnFSM", typeof (TTNIssueReturnFSMType))]
    [XmlElement("TTNShipmentFSM", typeof (TTNShipmentFSMType))]
    [XmlElement("TTNShipmentReturnFSM", typeof (TTNShipmentReturnFSMType))]
    [XmlElement("Ticket", typeof (TicketType))]
    [XmlElement("TicketRMCheck", typeof (TicketRMCheckType))]
    [XmlElement("TransferFromShop", typeof (TransferFromShopType))]
    [XmlElement("TransferToShop", typeof (TransferToShopType))]
    [XmlElement("WayBill", typeof (WayBillType))]
    [XmlElement("WayBillAct", typeof (WayBillActType))]
    [XmlElement("WayBillAct_v2", typeof (WayBillActType_v2))]
    [XmlElement("WayBillAct_v3", typeof (WayBillActType_v3))]
    [XmlElement("WayBillAct_v4", typeof (WayBillActType_v4))]
    [XmlElement("WayBill_v2", typeof (WayBillType_v2))]
    [XmlElement("WayBill_v3", typeof (WayBillType_v3))]
    [XmlElement("WayBill_v4", typeof (WayBillType_v4))]
    [XmlChoiceIdentifier("ItemElementName")]
    public object Item
    {
      get => this.itemField;
      set => this.itemField = value;
    }

    [XmlIgnore]
    public ItemChoiceType ItemElementName
    {
      get => this.itemElementNameField;
      set => this.itemElementNameField = value;
    }
  }
}
